Separate response and homegraph states
This fixes the following error:

```
ERROR:: QUERY FAILED: {}
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
```

Homegraph ReportState does not expect to get `status=SUCCESS` but only
device state as mentioned here: https://github.com/actions-on-google/actions-on-google-java/blob/7f3b1e2fd51e3b044380ea3c72722058ad99240f/src/main/proto/google/home/graph/v1/homegraph.proto#L132